require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PpcreviewsController do

  # This should return the minimal set of attributes required to create a valid
  # Ppcreview. As you add validations to Ppcreview, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PpcreviewsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ppcreviews as @ppcreviews" do
      ppcreview = Ppcreview.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ppcreviews).should eq([ppcreview])
    end
  end

  describe "GET show" do
    it "assigns the requested ppcreview as @ppcreview" do
      ppcreview = Ppcreview.create! valid_attributes
      get :show, {:id => ppcreview.to_param}, valid_session
      assigns(:ppcreview).should eq(ppcreview)
    end
  end

  describe "GET new" do
    it "assigns a new ppcreview as @ppcreview" do
      get :new, {}, valid_session
      assigns(:ppcreview).should be_a_new(Ppcreview)
    end
  end

  describe "GET edit" do
    it "assigns the requested ppcreview as @ppcreview" do
      ppcreview = Ppcreview.create! valid_attributes
      get :edit, {:id => ppcreview.to_param}, valid_session
      assigns(:ppcreview).should eq(ppcreview)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ppcreview" do
        expect {
          post :create, {:ppcreview => valid_attributes}, valid_session
        }.to change(Ppcreview, :count).by(1)
      end

      it "assigns a newly created ppcreview as @ppcreview" do
        post :create, {:ppcreview => valid_attributes}, valid_session
        assigns(:ppcreview).should be_a(Ppcreview)
        assigns(:ppcreview).should be_persisted
      end

      it "redirects to the created ppcreview" do
        post :create, {:ppcreview => valid_attributes}, valid_session
        response.should redirect_to(Ppcreview.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ppcreview as @ppcreview" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ppcreview.any_instance.stub(:save).and_return(false)
        post :create, {:ppcreview => {  }}, valid_session
        assigns(:ppcreview).should be_a_new(Ppcreview)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ppcreview.any_instance.stub(:save).and_return(false)
        post :create, {:ppcreview => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ppcreview" do
        ppcreview = Ppcreview.create! valid_attributes
        # Assuming there are no other ppcreviews in the database, this
        # specifies that the Ppcreview created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ppcreview.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => ppcreview.to_param, :ppcreview => { "these" => "params" }}, valid_session
      end

      it "assigns the requested ppcreview as @ppcreview" do
        ppcreview = Ppcreview.create! valid_attributes
        put :update, {:id => ppcreview.to_param, :ppcreview => valid_attributes}, valid_session
        assigns(:ppcreview).should eq(ppcreview)
      end

      it "redirects to the ppcreview" do
        ppcreview = Ppcreview.create! valid_attributes
        put :update, {:id => ppcreview.to_param, :ppcreview => valid_attributes}, valid_session
        response.should redirect_to(ppcreview)
      end
    end

    describe "with invalid params" do
      it "assigns the ppcreview as @ppcreview" do
        ppcreview = Ppcreview.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ppcreview.any_instance.stub(:save).and_return(false)
        put :update, {:id => ppcreview.to_param, :ppcreview => {  }}, valid_session
        assigns(:ppcreview).should eq(ppcreview)
      end

      it "re-renders the 'edit' template" do
        ppcreview = Ppcreview.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ppcreview.any_instance.stub(:save).and_return(false)
        put :update, {:id => ppcreview.to_param, :ppcreview => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ppcreview" do
      ppcreview = Ppcreview.create! valid_attributes
      expect {
        delete :destroy, {:id => ppcreview.to_param}, valid_session
      }.to change(Ppcreview, :count).by(-1)
    end

    it "redirects to the ppcreviews list" do
      ppcreview = Ppcreview.create! valid_attributes
      delete :destroy, {:id => ppcreview.to_param}, valid_session
      response.should redirect_to(ppcreviews_url)
    end
  end

end
